# use the shared Yast defaults
inherit_from:
  /usr/share/YaST2/data/devtools/data/rubocop-1.24.1_yast_style.yml

AllCops:
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  Enabled: false

# TODO: this need some non-trivial refactoring...
Metrics/AbcSize:
  Max: 111

# TODO: this need some non-trivial refactoring...
Metrics/BlockNesting:
  Max: 5

# TODO: this need some non-trivial refactoring...
Metrics/ClassLength:
  Max: 490

# TODO: this need some non-trivial refactoring...
Metrics/CyclomaticComplexity:
  Max: 25

Layout/LineLength:
  Max: 100

# TODO: this need some non-trivial refactoring...
Metrics/MethodLength:
  Max: 96

# TODO: this need some non-trivial refactoring...
Metrics/PerceivedComplexity:
  Max: 25

# FIXME: It seems the cop does not handle this complex case correctly,
# disable it for now on that file.
Lint/ShadowedException:
  Exclude:
    - 'src/lib/registration/connect_helpers.rb'

# Offense count: 5
Naming/AccessorMethodName:
  Enabled: false

# Offense count: 29
Style/Documentation:
  Enabled: false

# Offense count: 1
# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Naming/PredicateName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

# Let lslezak decide what to do with it. In general jreidinger does not see it as such big violence of style
Style/StructInheritance:
  Enabled: false

# Allow global mixins in tests
Style/MixinUsage:
  Exclude:
    - 'test/**/*.rb'

# this cop will change API, so disable it
Style/OptionalBooleanParameter:
  Enabled: false

# it sometimes make code harder to read
Style/GuardClause:
  Enabled: false

# disable missing ending range as it is not supported in ruby 2.7
# TODO: is it bug in rubocop that with target ruby version 2.7 it stil do it?
Style/SlicingWithRange:
  Enabled: false
