SummonGolem:
  spell_class: com.elmakers.mine.bukkit.action.builtin.SummonEntity
  parameters:
    entity_type: IRON_GOLEM
    power: 1000
    health: 20000
    duration: 3000
    target_self: true
  effects:
    cast:
      particle: VILLAGER_HAPPY
      radius: 5
  icon: IRON_BLOCK
  description: "Triệu hồi một Golem để hỗ trợ bạn trong chiến đấu."

